version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=globetrek
      - POSTGRES_USER=localix
      - POSTGRES_PASSWORD=localix_password
    ports:
      - "5433:5432" # Changed to 5433 to avoid conflict with local Postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localix -d globetrek"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=globetrek
      - DB_USER=localix
      - DB_PASSWORD=localix_password
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=True
    restart: always

volumes:
  postgres_data:
